### ISSUE TITLE
管理导航链接下的筛选功能无效

### ISSUE THREAD

**Issue by eonegh** [gogobody/WebStack#2]
管理导航链接页面下的筛选功能无效，例如搜索V2EX，则返回“.../admin/extending.php?keywords=V2EX&category=”，并报404错误。还有一个小问题：自动暗黑模式时，顶部导航栏依旧是白色，强制刷新浏览器后就自动改正过来。谢谢！

**Comment by hkylin** [comment]
也遇到了这个问题，貌似是跳转时候URL不对，如果是WebStack/pages/admin/manage-navi.php&keywords=V2EX&category=就正常;代码中没看到是哪儿在处理。。。。@gogobody

**Comment by gogobody** [comment]
修复了
