### ISSUE TITLE
首页不能显示分类下的文章

### ISSUE THREAD

**Issue by redrohu** [gogobody/WebStack#3]
![捕获1](https://user-images.githubusercontent.com/29138817/116807964-bebdf280-ab68-11eb-876a-a99621736e49.PNG)
![捕获2](https://user-images.githubusercontent.com/29138817/116807966-bfef1f80-ab68-11eb-91c5-6d79f34518fa.PNG)

**Comment by gogobody** [comment]
浏览下插件设置

**Comment by redrohu** [comment]
![11](https://user-images.githubusercontent.com/29138817/116808424-46a4fc00-ab6b-11eb-9072-a85707ef83ff.PNG)

**Comment by gogobody** [comment]
主题设置，外观设置，其他设置里填写
